name: Train and Evaluate Model

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs'
        required: true
        default: 100

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn tensorflow sacred pymongo

      - name: Train and evaluate model
        run: |
          python model.py with epochs=${{ github.event.inputs.epochs }}
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
